/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.2.0. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module InstructionRAM 
    ( // Inputs
      input  CLOCK // clock
    , input  RESET // reset 
    , input  ENABLE // chip enable signal
    , input [31:0] PCF // current PC, in Byte address
      // Outputs
    , output reg [31:0] Instr // fetched instruction
    );

  // blockRamFile begin
  reg [31:0] RAM [0:511];
  integer i;

  // reset IM
  always @(RESET) begin 
    if (RESET == 1) begin
      Instr <= 32'b0000_0000_0000_0000_0000_0000_0011_1111; // bubble instruction reset
      $readmemb("instructions.bin",RAM); // read instructions
    end
  end

  // negedge triggered IF
  always @(negedge CLOCK) begin
    if (ENABLE) begin
      if ((0 <= PCF) && (PCF < 2048)) begin // if PCF is valid
        // $display("fetching the %dth ins", PCF/4);
        Instr <= RAM[(PCF/4)]; // fetch instruction to output
      end
    end
  end

endmodule


